services:
  - type: web
    name: my-django-app
    env: python
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn manage.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
